LEGAL_SYNONYMS = {
    # DOMAIN 1: TERMINATION / DISMISSAL / SECURITY OF TENURE
    "tinanggal ako sa trabaho":         ["termination", "security of tenure"],
    "sinibak ako sa trabaho":           ["dismissal", "security of tenure"],
    "tinanggal ako":                    ["termination", "dismissal"],
    "sinibak ako":                      ["dismissal", "termination"],
    "tinerminate ako":                  ["termination", "dismissal"],
    "na fired ako":                     ["dismissal", "termination"],
    "pinaalis ako":                     ["dismissal", "termination"],
    "pinatanggal ako":                  ["dismissal", "termination"],
    "na-dismiss ako":                   ["dismissal", "termination"],
    "na-terminate ako":                 ["termination", "dismissal"],
    "na-layoff ako":                    ["reduction of personnel", "retrenchment"],
    "na-retrench ako":                  ["reduction of personnel", "retrenchment"],
    "tinanggal nang walang dahilan":    ["security of tenure", "just causes"],
    "basta na lang ako tinanggal":      ["security of tenure", "just causes"],
    "walang dahilan tinanggal ako":     ["security of tenure", "just causes"],
    "puwede bang tanggalin ako nang walang dahilan": ["security of tenure"],
    "pwede ba akong tanggalin ng boss ko": ["termination", "security of tenure"],
    "pwede ba akong tanggalin ng amo ko": ["termination", "security of tenure"],
    "ayaw na ako papasukin sa trabaho": ["constructive dismissal", "termination"],
    "pinilit akong magresign":          ["constructive dismissal", "resignation"],
    "gustong ipatanggal sa trabaho":    ["termination", "security of tenure"],

    # Disease / Illness
    "tinanggal ako dahil sa sakit":         ["disease as ground for termination"],
    "pinaalis ako dahil nagkasakit ako":    ["disease as ground for termination"],
    "tinanggal ako dahil may sakit ako":    ["disease as ground for termination"],
    "pwede ba akong tanggalin dahil may sakit": ["disease as ground for termination"],
    "maaari bang itiwalag dahil may karamdaman": ["disease as ground for termination"],

    # Resignation
    "nagresign ako":                    ["termination by employee", "resignation"],
    "pwede ba akong magresign":         ["termination by employee", "resignation"],
    "gustong magresign pero pinipigilan": ["termination by employee"],
    "nagbitiw ako sa trabaho":          ["termination by employee", "resignation"],
    "gusto kong umalis sa trabaho":     ["termination by employee", "resignation"],

    # Closure / Retrenchment
    "isasara na ang kumpanya":          ["closure of establishment", "reduction of personnel"],
    "magsasara ang kompanya":           ["closure of establishment", "reduction of personnel"],
    "may retrenchment":                 ["reduction of personnel", "retrenchment"],
    "nagrereklamo tungkol sa retrenchment": ["reduction of personnel", "retrenchment"],

    # Status
    "probationary ako tapos tinanggal": ["probationary employment", "termination"],
    "hindi ako na regularize":          ["probationary employment", "regular employment"],
    "kailan ako magiging regular":      ["regular employment", "probationary employment"],
    "contractual lang ba ako habang buhay": ["regular employment", "casual employment"],

    # Separation / Backwages
    "may separation pay ba ako":            ["separation pay"],
    "makakakuha ba ako ng separation pay":  ["separation pay"],
    "hindi binigay ang separation pay":     ["separation pay"],
    "magkano ang separation pay ko":        ["separation pay"],
    "gusto ko ipabalik sa trabaho":         ["reinstatement"],
    "pwede ba akong ibalik sa trabaho":     ["reinstatement"],
    "may backpay ba ako":                   ["backwages", "separation pay"],

    # DOMAIN 2: WAGES / SALARIES / DEDUCTIONS
    "hindi ako pinasahod":          ["non-payment of wages", "wages"],
    "hindi ako binayaran":          ["non-payment of wages", "wages"],
    "hindi binigay ang sahod":      ["non-payment of wages", "wages"],
    "hindi binigay ang sweldo":     ["non-payment of wages", "wages"],
    "kulang ang sahod ko":          ["minimum wages", "wages"],
    "kulang ang sweldo ko":         ["minimum wages", "wages"],
    "baba sa minimum wage ang sahod ko": ["minimum wages"],
    "hindi umabot sa minimum wage": ["minimum wages"],
    "wala pang minimum wage ang sahod": ["minimum wages"],
    "late binabayaran ang sahod":           ["time of payment", "wages"],
    "hindi sa oras binabayaran ang sweldo": ["time of payment", "wages"],
    "release ng sweldo":                    ["time of payment", "wages"],
    "mag-release ng sweldo":                ["time of payment", "wages"],
    "kailan dapat magpasahod":              ["time of payment", "wages"],
    "may binabawas sa sahod ko":        ["wage deduction", "deductions"],
    "may kaltas sa sweldo":             ["wage deduction", "deductions"],
    "pinapipirma ako ng blanko na papel": ["wage deduction", "withholding"],
    "kinakaltasan ako ng sobra":        ["wage deduction", "deductions"],
    "ipitin ang sahod":                 ["withholding of wages"],
    "hindi ibigay ang sahod":           ["withholding of wages", "wages"],
    "hindi ibigay ang sweldo":          ["withholding of wages", "wages"],
    "hindi ibigay":                     ["withholding of wages"],
    "hindi ako binigyan ng payslip":    ["wages", "form of payment"],
    "pinagbabayad ako ng bond":         ["deposits for loss or damage"],
    "nasa cash ba dapat ang bayad":     ["form of payment", "wages"],

    # DOMAIN 3: HOURS / OVERTIME / REST / LEAVES
    "nagovertime ako":                      ["overtime", "overtime pay"],
    "nag overtime ako":                     ["overtime", "overtime pay"],
    "pinag overtime ako":                   ["overtime", "overtime pay"],
    "hindi binayaran ang overtime":         ["overtime pay"],
    "walang overtime pay":                  ["overtime pay"],
    "sobra sa walong oras ang trabaho ko":  ["normal hours of work", "overtime"],
    "pinapagawa ako ng sobra sa oras":      ["normal hours of work", "overtime work"],
    "walang break time":                ["meal periods"],
    "walang pahinga sa trabaho":        ["meal periods", "rest day"],
    "pinapasok ako kahit rest day":     ["rest day", "work on rest day"],
    "pinapasok ako sa bakasyon ko":     ["rest day", "service incentive leave"],
    "gabi ako nagtatrabaho":        ["night-shift differential"],
    "may night differential ba":    ["night-shift differential"],
    "walang night differential":    ["night-shift differential"],
    "gabi nagtatrabaho":            ["night-shift differential"],
    "may holiday pay ba ako":       ["holiday pay"],
    "bayad ba kapag holiday":       ["holiday pay"],
    "pinapasok ako ng holiday":     ["holiday pay", "premium pay"],
    "walang holiday pay":           ["holiday pay"],
    "bayad sa pista opisyal":       ["holiday pay"],
    "nagleave ako":                     ["service incentive leave"],
    "nag leave ako":                    ["service incentive leave"],
    "pwede ba akong mag leave":         ["service incentive leave"],
    "ilang araw ba ang leave ko":       ["service incentive leave"],
    "hindi binayaran ang leave ko":     ["service incentive leave"],
    "may sick leave ba ako":            ["service incentive leave"],
    "may vacation leave ba ako":        ["service incentive leave"],
    "hindi binibigyan ng leave":        ["service incentive leave"],

    # DOMAIN 4: SPECIAL GROUPS (Women, Minors, Kasambahay)
    "buntis ako pwede pa ba ako magtrabaho":        ["maternity leave benefits", "facilities for women"],
    "may maternity leave ba ako":                   ["maternity leave benefits"],
    "tinanggal ako dahil buntis ako":               ["discrimination prohibited", "maternity leave benefits"],
    "pinaalis ako dahil buntis":                    ["discrimination prohibited", "maternity leave benefits"],
    "pinipilit ako magresign dahil buntis":         ["discrimination prohibited", "constructive dismissal"],
    "hindi ako pinapasok dahil babae ako":          ["discrimination prohibited"],
    "may diskriminasyon sa babae sa trabaho":       ["discrimination prohibited"],
    "bawal ba mag-asawa habang nagtatrabaho":       ["stipulation against marriage"],
    "pinaaalis ang mga buntis na manggagawa":       ["discrimination prohibited", "maternity leave benefits"],
    "tanggalin dahil buntis":                       ["discrimination prohibited", "maternity leave benefits"],
    "menor de edad pwede ba magtrabaho":            ["minimum employable age"],
    "bata pa pwede na bang magtrabaho":             ["minimum employable age"],
    "pinagtatrabaho ang anak ko na menor de edad":  ["minimum employable age", "child labor"],
    "ilang taong gulang para makapagtrabaho":       ["minimum employable age"],
    "kasambahay ako":                               ["househelpers", "domestic service"],
    "katulong ako sa bahay":                            ["househelpers", "domestic service"],
    "hindi ako binayaran bilang kasambahay":            ["minimum cash wage", "househelpers"],
    "tinanggal ako bilang kasambahay":                  ["indemnity for unjust termination of services"],
    "hindi ako pinapapasok sa paaralan bilang kasambahay": ["opportunity for education"],
    "minimum wage ng kasambahay":                       ["minimum cash wage", "househelpers"],
    "sahod ng katulong":                                ["minimum cash wage", "househelpers"],
    "sino nagtatakda ng sahod ng kasambahay":           ["minimum cash wage", "househelpers"],
    "apprentice ako":       ["apprenticeship agreement", "qualifications of apprentice"],
    "learner ako sa trabaho": ["learners defined", "learnership agreement"],

    # DOMAIN 5: SAFETY / HEALTH / DISABILITY
    "walang first aid sa trabaho":          ["first-aid treatment"],
    "delikado ang trabaho namin":           ["safety and health standards"],
    "walang safety equipment":              ["safety and health standards"],
    "walang protective equipment":          ["safety and health standards"],
    "delikado ang aming lugar ng trabaho":  ["safety and health standards"],
    "safe workplace":                       ["safety and health standards", "safe and healthful working conditions"],
    "kaligtasan sa trabaho":                ["safety and health standards"],
    "nasaktan ako sa trabaho":                              ["safety and health standards", "compulsory coverage"],
    "aksidente ako sa trabaho":                             ["compulsory coverage", "employees compensation commission"],
    "nagkasakit ako dahil sa trabaho":                      ["compulsory coverage", "disease"],
    "namatay ang katrabaho ko sa aksidente":                ["employees compensation commission", "death"],
    "nagdisability ako dahil sa trabaho":                   ["permanent total disability", "permanent partial disability"],
    "pansamantalang hindi makapagtrabaho dahil sa injury":  ["temporary total disability"],
    "may disability benefits ba ako":                       ["disability", "employees compensation commission"],
    "pwede ba akong maka claim ng compensation":    ["settlement of claims", "employees compensation commission"],
    "hindi ako binigyan ng benepisyo":              ["employee benefits"],
    "wala akong sss":                               ["compulsory coverage"],
    "walang philhealth":                            ["compulsory coverage"],
    "walang pag ibig":                              ["compulsory coverage"],
    "binawasan ang benefits ko":            ["non-diminution of benefits"],
    "binawasan ang mga benepisyo namin":    ["non-diminution of benefits"],
    "tinanggal ang benepisyo namin":        ["non-diminution of benefits"],

    # DOMAIN 6: COMPLAINTS / JURISDICTION
    "gusto ko magsampa ng kaso sa trabaho": ["jurisdiction of the labor arbiters and the commission", "money claims"],
    "magsampa ng reklamo":                  ["jurisdiction of the labor arbiters and the commission", "money claims"],
    "saan pwedeng magsampa":                ["jurisdiction of the labor arbiters and the commission"],
    "saan pwede magsampa":                  ["jurisdiction of the labor arbiters and the commission"],
    "saan pwedeng magreklamo":              ["jurisdiction of the labor arbiters and the commission"],
    "saan ako pwede magreklamo":            ["jurisdiction of the labor arbiters and the commission"],
    "paano ako makakademanda sa boss ko":   ["money claims"],
    "may kaso ako sa employer ko":          ["jurisdiction of the labor arbiters and the commission"],
    "paano magreklamo sa dole":             ["visitorial and enforcement power"],
    "pwede bang mag inspect ang dole":      ["visitorial and enforcement power"],
    "pwede bang magsumbong sa dole":        ["visitorial and enforcement power"],
    "sasabihan ko ang dole tungkol sa employer ko": ["visitorial and enforcement power"],
    "mag-file ng kaso":                     ["jurisdiction of the labor arbiters and the commission", "money claims"],
    "magfile ng kaso":                      ["jurisdiction of the labor arbiters and the commission", "money claims"],
    "file ng kaso":                         ["jurisdiction of the labor arbiters and the commission", "money claims"],
    "kaso sa boss":                         ["jurisdiction of the labor arbiters and the commission"],
    "saan dalhin ang reklamo sa trabaho":   ["jurisdiction of the labor arbiters and the commission"],

    # DOMAIN 7: RETIREMENT
    "magreretiro na ako":           ["retirement"],
    "may retirement pay ba ako":    ["retirement"],
    "hindi binigay ang retirement pay": ["retirement"],
    "magkano ang retirement pay":   ["retirement"],
    "paano ang retirement":         ["retirement"],

    # DOMAIN 8: GOVERNMENT EMPLOYEES (EXCLUSIONS)
    "government employee ako may problema sa trabaho":  ["government employees", "civil service", "coverage"],
    "empleyado ako ng gobyerno may reklamo":            ["government employees", "civil service", "coverage"],
    "government employee ako":                          ["government employees", "civil service", "coverage"],
    "empleyado ng gobyerno":                            ["government employees", "civil service", "coverage"],
    "kawani ng gobyerno":                               ["government employees", "civil service", "coverage"],
    "sahod para sa mga government employees":           ["government employees", "civil service", "coverage"],
    "sahod ng government employees":                    ["government employees", "civil service", "coverage"],
    "sahod ng kawani ng gobyerno":                      ["government employees", "civil service", "coverage"],

    # DOMAIN 9: RECRUITMENT / OVERSEAS
    "nadaya ako sa recruitment agency":         ["illegal recruitment"],
    "iligal na recruiter":                      ["illegal recruitment"],
    "pinapabayad ako ng sobra sa agency":       ["illegal recruitment", "prohibited practices"],
    "walang lisensya ang agency":               ["illegal recruitment", "registration"],
    "gustong mag abroad paano mag apply":       ["overseas employment"],

    # DOMAIN 10: UNIONS / CBA / STRIKES
    "gusto naming magtayo ng unyon":                ["self-organization", "labor organization"],
    "hindi kami pinapayagan magtayo ng union":      ["unfair labor practices of employers", "self-organization"],
    "may cba ba kami":                              ["collective bargaining agreement"],
    "gustong mag-strike":                           ["strikes picketing and lockouts"],
    "pwede ba kami mag welga":                      ["strikes picketing and lockouts"],
    "na-lockout kami":                              ["strikes picketing and lockouts"],

    # DOMAIN 11: CONTRACTING
    "agency worker ako":                        ["contractor or subcontractor", "indirect employer"],
    "kontraktwal ako sa ibang kumpanya":        ["contractor or subcontractor", "indirect employer"],
    "galing ako sa manpower agency":            ["contractor or subcontractor", "indirect employer"],
    "labor only contracting ba ito":            ["contractor or subcontractor"],
    "sino may pananagutan sa kontraktwal":      ["solidary liability", "indirect employer"],
    "sino may pananagutan kung hindi binayaran ng agency": ["solidary liability"],

    # DOMAIN 12: ATTORNEY'S FEES
    "may abogado ba ako kailangan sa kaso":     ["attorney's fees"],
    "kailangan ko ba ng abogado sa reklamo":    ["attorney's fees"],
    "magkano babayaran ko sa abogado":          ["attorney's fees"],

    # DISCRIMINATION
    "may harassment sa trabaho":            ["discrimination prohibited"],
    "nire-report ako pero walang aksyon":   ["discrimination prohibited"],
    "may diskriminasyon sa edad":           ["discrimination prohibited"],
    "may diskriminasyon sa kasarian":       ["discrimination prohibited"],

    # GENERAL RIGHTS
    "ano ang karapatan ko bilang empleyado": ["declaration of basic policy", "security of tenure"],
    "ano karapatan ko sa trabaho":           ["declaration of basic policy"],

    # CANONICAL SINGLE WORDS
    "sahod":        ["wages"],
    "sweldo":       ["wages"],
    "suweldo":      ["wages"],
    "bayad":        ["wages"],
    "kabayaran":    ["wages"],
    "kita":         ["earnings"],
    "kinita":       ["earnings"],
    "kaltas":       ["deduction"],
    "kinaltas":     ["deduction"],
    "kinaltasan":   ["deduction"],
    "kaltasan":     ["deduction"],
    "binawas":      ["deduction"],
    "binawasan":    ["deduction"],
    "bawasan":      ["deduction"],
    "kulang":       ["underpayment"],
    "pigil":        ["withholding"],
    "pinigil":      ["withholding"],
    "pinipigil":    ["withholding"],
    "ipitin":       ["withholding of wages"],
    "trabaho":      ["employment"],
    "pasok":        ["work"],
    "empleyo":      ["employment"],
    "hanapbuhay":   ["employment"],
    "empleyado":        ["employee"],
    "empleado":         ["employee"],
    "manggagawa":       ["worker"],
    "mangagawa":        ["worker"],
    "trabahador":       ["worker"],
    "amo":          ["employer"],
    "patron":       ["employer"],
    "boss":         ["employer"],
    "kumpanya":     ["establishment"],
    "kompanya":     ["establishment"],
    "negosyo":      ["enterprise"],
    "oras":         ["hours of work"],
    "overtime":     ["overtime pay"],
    "lampas":       ["overtime"],
    "lagpas":       ["overtime"],
    "dagdag":       ["additional compensation"],
    "undertime":    ["undertime work"],
    "pahinga":      ["rest period"],
    "break":        ["rest period"],
    "holiday":      ["holiday pay"],
    "bakasyon":     ["vacation leave"],
    "leave":        ["service incentive leave"],
    "gabi":             ["night-shift differential"],
    "night":            ["night-shift differential"],
    "night shift":      ["night-shift differential"],
    "night differential": ["night-shift differential"],
    "sakit":        ["illness"],
    "karamdaman":   ["disease"],
    "kalusugan":    ["health"],
    "buntis":       ["maternity leave benefits", "discrimination prohibited"],
    "tanggal":      ["termination"],
    "tinanggal":    ["termination"],
    "natanggal":    ["termination"],
    "sinibak":      ["dismissal"],
    "sibak":        ["dismissal"],
    "talsik":       ["termination"],
    "pinaalis":     ["termination"],
    "terminate":    ["termination"],
    "regular":      ["regular employment"],
    "permanente":   ["regular employment"],
    "probationary": ["probationary employment"],
    "probation":    ["probationary employment"],
    "casual":       ["casual employment"],
    "contractual":  ["contractual"],
    "kontraktwal":  ["contractual"],
    "kontrata":     ["contract"],
    "apprentice":       ["apprenticeship"],
    "learner":          ["learners"],
    "trainee":          ["apprenticeship"],
    "balik":        ["reinstatement"],
    "ibalik":       ["reinstatement"],
    "backpay":      ["backwages"],
    "backwages":    ["backwages"],
    "separation":   ["separation pay"],
    "retrenchment": ["retrenchment"],
    "redundancy":   ["redundancy"],
    "resign":       ["resignation"],
    "nagresign":    ["resignation"],
    "magresign":    ["resignation"],
    "bitiw":        ["resignation"],
    "nagbitiw":     ["resignation"],
    "hire":         ["hiring"],
    "hiring":       ["hiring"],
    "recruit":      ["recruitment"],
    "recruitment":  ["recruitment"],
    "recruiter":    ["recruitment"],
    "agency":       ["placement"],
    "placement":    ["placement"],
    "lisensya":     ["license"],
    "permit":       ["permit"],
    "rehistro":     ["registration"],
    "abroad":   ["overseas employment"],
    "OFW":      ["overseas employment"],
    "ofw":      ["overseas employment"],
    "overseas": ["overseas employment"],
    "seaman":   ["seaman"],
    "seafarer": ["seaman"],
    "kaligtasan":   ["safety"],
    "panganib":     ["hazard"],
    "hazard":       ["hazard"],
    "peligro":      ["hazard"],
    "aksidente":    ["accident"],
    "injury":       ["injury"],
    "sugat":        ["injury"],
    "disability":   ["disability"],
    "diskriminasyon":   ["discrimination"],
    "discrimination":   ["discrimination"],
    "kasambahay":   ["househelpers"],
    "katulong":     ["househelpers"],
    "unyon":        ["labor organization"],
    "union":        ["labor organization"],
    "samahan":      ["labor organization"],
    "welga":        ["strike"],
    "strike":       ["strike"],
    "piket":        ["picketing"],
    "lockout":      ["lockout"],
    "CBA":          ["collective bargaining agreement"],
    "cba":          ["collective bargaining agreement"],
    "negosasyon":   ["collective bargaining"],
    "retiro":       ["retirement"],
    "retire":       ["retirement"],
    "reklamo":      ["complaint"],
    "kaso":         ["case"],
    "alitan":       ["dispute"],
    "grievance":    ["grievance"],
    "areglo":       ["settlement"],
    "mediation":    ["mediation"],
    "arbitration":  ["arbitration"],
    "conciliation": ["conciliation"],
    "sampa":        ["filing"],
    "magsampa":     ["filing a complaint"],
    "DOLE":         ["Department of Labor and Employment"],
    "dole":         ["Department of Labor and Employment"],
    "NLRC":         ["National Labor Relations Commission"],
    "nlrc":         ["National Labor Relations Commission"],
    "arbiter":      ["Labor Arbiter"],
    "SSS":          ["Social Security System"],
    "GSIS":         ["Government Service Insurance System"],
    "karapatan":        ["rights"],
    "tungkulin":        ["duty"],
    "obligasyon":       ["obligation"],
    "responsibilidad":  ["responsibility"],
    "proteksyon":       ["protection"],
    "seguridad":        ["security"],
    "inspect":          ["inspection"],
    "inspeksyon":       ["inspection"],
    "paggawa":          ["labor"],
    "labor":            ["labor"],
    "walang dahilan":   ["security of tenure", "just causes"],
}