# synonyms.py

LEGAL_SYNONYMS = {
    # =========================
    # PHRASES
    # =========================
    "tinanggal ako sa trabaho": ["termination of employment", "dismissal", "security of tenure"],
    "sinibak ako sa trabaho": ["dismissal", "termination of employment"],
    "tinanggal ako": ["termination of employment", "dismissal"],
    "sinibak ako": ["dismissal", "termination of employment"],
    "tinerminate ako": ["termination", "dismissal"],
    "na fired ako": ["dismissal", "termination"],
    "basta na lang ako tinanggal": ["termination by employer", "security of tenure", "illegal dismissal"],
    "walang dahilan tinanggal ako": ["termination by employer", "security of tenure"],
    "pwede ba akong tanggalin ng boss ko": ["employer", "termination", "dismissal", "security of tenure"],
    "pwede ba akong tanggalin ng amo ko": ["employer", "termination", "dismissal"],
    "ayaw na ako papasukin sa trabaho": ["termination by employer", "constructive dismissal"],
    "tinanggal ako dahil sa sakit": ["disease as ground for termination"],
    "pinaalis ako dahil nagkasakit ako": ["disease as ground for termination"],
    "nagresign ako": ["termination by employee", "resignation"],
    "pwede ba akong magresign": ["termination by employee"],
    "gustong magresign pero pinipigilan": ["termination by employee"],
    "isasara na ang kumpanya": ["closure of establishment", "reduction of personnel"],
    "magsasara ang kompanya": ["closure of establishment", "reduction of personnel"],
    "may retrenchment": ["closure of establishment", "reduction of personnel"],
    "na retrench ako": ["reduction of personnel", "closure of establishment"],
    "probationary ako tapos tinanggal": ["probationary employment", "termination by employer"],
    "hindi ako na regularize": ["probationary employment", "regular and casual employment"],
    "kailan ako magiging regular": ["regular and casual employment", "probationary employment"],
    "contractual lang ba ako habang buhay": ["regular and casual employment", "probationary employment"],
    "may separation pay ba ako": ["separation pay"],
    "makakakuha ba ako ng separation pay": ["separation pay"],
    "hindi binigay ang separation pay": ["separation pay", "termination"],
    "magkano ang separation pay ko": ["separation pay"],
    "hindi ako pinasahod": ["non-payment of wages", "payment of wages", "wages"],
    "hindi ako binayaran": ["non-payment of wages", "payment of wages", "wages"],
    "hindi binigay ang sahod": ["non-payment of wages", "payment of wages", "wages"],
    "hindi binigay ang sweldo": ["non-payment of wages", "payment of wages", "wages"],
    "kulang ang sahod ko": ["wages", "payment of wages", "underpayment", "regional minimum wages"],
    "kulang ang sweldo ko": ["wages", "regional minimum wages", "underpayment"],
    "baba sa minimum wage ang sahod ko": ["regional minimum wages", "wages"],
    "hindi umabot sa minimum wage": ["regional minimum wages"],
    "late binabayaran ang sahod": ["time of payment", "wages"],
    "hindi sa oras binabayaran ang sweldo": ["time of payment"],
    "may binabawas sa sahod ko": ["wage deduction", "deductions for loss or damage"],
    "may kaltas sa sweldo": ["wage deduction"],
    "pinapipirma ako ng blanko na papel": ["wage deduction", "withholding of wages and kickbacks prohibited"],
    "kinakaltasan ako ng sobra": ["wage deduction", "limitations"],
    "hindi ako binigyan ng payslip": ["wages", "form of payment"],
    "pinagbabayad ako ng bond": ["deposits for loss or damage"],
    "nagovertime ako": ["overtime", "overtime pay", "hours of work"],
    "nag overtime ako": ["overtime", "overtime pay", "hours of work"],
    "pinag overtime ako": ["overtime", "overtime pay", "hours of work"],
    "hindi binayaran ang overtime": ["overtime pay", "payment of overtime"],
    "walang overtime pay": ["overtime pay"],
    "sobra sa walong oras ang trabaho ko": ["normal hours of work", "overtime"],
    "pinapagawa ako ng sobra sa oras": ["normal hours of work", "overtime work"],
    "walang break time": ["meal periods"],
    "walang pahinga sa trabaho": ["meal periods", "right to weekly rest day"],
    "pinapasok ako kahit rest day": ["right to weekly rest day", "when employer may require work on a rest day"],
    "pinapasok ako sa bakasyon ko": ["right to weekly rest day"],
    "gabi ako nagtatrabaho": ["night-shift differential"],
    "may night differential ba": ["night-shift differential"],
    "walang night differential": ["night-shift differential"],
    "may holiday pay ba ako": ["holiday pay", "premium pay"],
    "bayad ba kapag holiday": ["holiday pay", "premium pay"],
    "pinapasok ako ng holiday": ["compensation for rest day sunday or holiday work", "holiday pay"],
    "walang holiday pay": ["right to holiday pay"],
    "nagleave ako": ["leave", "service incentive leave"],
    "nag leave ako": ["leave", "service incentive leave"],
    "pwede ba akong mag leave": ["leave", "service incentive leave"],
    "ilang araw ba ang leave ko": ["service incentive leave"],
    "hindi binayaran ang leave ko": ["service incentive leave"],
    "may sick leave ba ako": ["service incentive leave"],
    "may vacation leave ba ako": ["service incentive leave"],
    "buntis ako pwede pa ba ako magtrabaho": ["facilities for women", "maternity leave benefits"],
    "may maternity leave ba ako": ["maternity leave benefits"],
    "tinanggal ako dahil buntis ako": ["maternity leave benefits", "discrimination prohibited"],
    "pinaalis ako dahil buntis": ["discrimination prohibited", "maternity leave benefits"],
    "pinipilit ako magresign dahil buntis": ["stipulation against marriage", "discrimination prohibited"],
    "hindi ako pinapasok dahil babae ako": ["discrimination prohibited"],
    "may diskriminasyon sa babae sa trabaho": ["discrimination prohibited", "classification of certain women workers"],
    "bawal ba mag-asawa habang nagtatrabaho": ["stipulation against marriage"],
    "menor de edad pwede ba magtrabaho": ["minimum employable age", "coverage"],
    "bata pa pwede na bang magtrabaho": ["minimum employable age"],
    "pinagtatrabaho ang anak ko na menor de edad": ["minimum employable age", "prohibition against child discrimination"],
    "apprentice ako": ["apprenticeship agreement", "qualifications of apprentice"],
    "learner ako sa trabaho": ["learners defined", "learnership agreement"],
    "kasambahay ako": ["contract of domestic service", "coverage"],
    "katulong ako sa bahay": ["contract of domestic service"],
    "hindi ako binayaran bilang kasambahay": ["minimum wage", "minimum cash wage"],
    "tinanggal ako bilang kasambahay": ["indemnity for unjust termination of services", "service of termination notice"],
    "hindi ako pinapapasok sa paaralan bilang kasambahay": ["opportunity for education"],
    "walang first aid sa trabaho": ["first-aid treatment"],
    "delikado ang trabaho namin": ["safety and health standards"],
    "walang safety equipment": ["safety and health standards"],
    "nasaktan ako sa trabaho": ["safety and health standards", "compulsory coverage"],
    "aksidente ako sa trabaho": ["compulsory coverage", "employees compensation commission"],
    "nagkasakit ako dahil sa trabaho": ["disease as ground for termination", "compulsory coverage"],
    "namatay ang katrabaho ko sa aksidente": ["death", "employees compensation commission"],
    "nagdisability ako dahil sa trabaho": ["permanent total disability", "permanent partial disability"],
    "pansamantalang hindi makapagtrabaho dahil sa injury": ["temporary total disability"],
    "pwede ba akong maka claim ng compensation": ["settlement of claims", "employees compensation commission"],
    "hindi ako binigyan ng benepisyo": ["employee benefits", "benefits"],
    "wala akong sss": ["compulsory coverage"],
    "walang philhealth": ["compulsory coverage"],
    "binawasan ang benefits ko": ["prohibition against elimination or diminution of benefits", "non-diminution of benefits"],
    "binawasan ang mga benepisyo namin": ["prohibition against elimination or diminution of benefits"],
    "magreretiro na ako": ["retirement"],
    "may retirement pay ba ako": ["retirement"],
    "hindi binigay ang retirement pay": ["retirement"],
    "gusto ko magsampa ng kaso sa trabaho": ["money claims", "jurisdiction of the labor arbiters and the commission"],
    "saan ako pwede magreklamo": ["jurisdiction of the labor arbiters and the commission", "recovery of wages simple money claims and other benefits"],
    "paano ako makakademanda sa boss ko": ["money claims", "institution of money claims"],
    "may kaso ako sa employer ko": ["jurisdiction of the labor arbiters and the commission"],
    "nadaya ako sa recruitment agency": ["illegal recruitment", "prohibited practices"],
    "iligal na recruiter": ["illegal recruitment"],
    "pinapabayad ako ng sobra sa agency": ["fees to be paid by workers", "illegal recruitment"],
    "walang lisensya ang agency": ["registration fees", "illegal recruitment"],
    "gustong mag abroad paano mag apply": ["overseas employment development board"],
    "gusto naming magtayo ng unyon": ["coverage and employees right to self-organization", "requirements of registration"],
    "hindi kami pinapayagan magtayo ng union": ["unfair labor practices of employers", "self-organization"],
    "may cba ba kami": ["collective bargaining agreement", "terms of a collective bargaining agreement"],
    "gustong mag-strike": ["strikes picketing and lockouts"],
    "pwede ba kami mag welga": ["strikes picketing and lockouts"],
    "na-lockout kami": ["strikes picketing and lockouts"],
    "may harassment sa trabaho": ["discrimination prohibited"],
    "nire-report ako pero walang aksyon": ["discrimination prohibited"],
    "may diskriminasyon sa edad": ["discrimination prohibited"],
    "ano ang karapatan ko bilang empleyado": ["declaration of basic policy", "security of tenure"],
    "ano karapatan ko sa trabaho": ["declaration of basic policy"],
    "agency worker ako": ["contractor or subcontractor", "indirect employer"],
    "kontraktwal ako sa ibang kumpanya": ["contractor or subcontractor", "indirect employer"],
    "galing ako sa manpower agency": ["contractor or subcontractor", "indirect employer"],
    "labor only contracting ba ito": ["contractor or subcontractor"],
    "sino may pananagutan sa kontraktwal": ["solidary liability", "indirect employer"],
    "sino may pananagutan kung hindi binayaran ng agency": ["solidary liability"],
    "government employee ako may problema sa trabaho": ["government employees"],
    "empleyado ako ng gobyerno may reklamo": ["government employees"],
    "may abogado ba ako kailangan sa kaso": ["attorney's fees"],
    "kailangan ko ba ng abogado sa reklamo": ["attorney's fees"],
    "magkano babayaran ko sa abogado": ["attorney's fees"],
    "paano magreklamo sa dole": ["visitorial and enforcement power"],
    "pwede bang mag inspect ang dole": ["visitorial and enforcement power"],
    "pwede bang magsumbong sa dole": ["visitorial and enforcement power"],
    "sasabihan ko ang dole tungkol sa employer ko": ["visitorial and enforcement power"],

    # =========================
    # SINGLE WORDS
    # =========================
    "sahod": ["wage", "salary", "compensation", "earnings", "remuneration"],
    "sweldo": ["wage", "salary", "compensation", "earnings", "remuneration"],
    "suweldo": ["wage", "salary", "compensation"],
    "bayad": ["payment", "wage", "compensation"],
    "kabayaran": ["payment", "compensation", "remuneration"],
    "binayaran": ["paid", "payment"],
    "bayaran": ["pay", "payment"],
    "nagbayad": ["paid", "payment"],
    "magbayad": ["pay", "payment"],
    "nabayaran": ["paid", "payment"],
    "kita": ["earnings"],
    "kinita": ["earnings"],
    "kumikita": ["earnings"],
    "kaltas": ["deduction"],
    "kinaltas": ["deduction"],
    "kinaltasan": ["deduction"],
    "kaltasan": ["deduction"],
    "binawas": ["deduction"],
    "binawasan": ["deduction"],
    "bawasan": ["deduction"],
    "nabawasan": ["deduction"],
    "kulang": ["underpayment", "unpaid wages"],
    "kulangan": ["underpayment", "unpaid wages"],
    "kumulang": ["underpayment"],
    "pigil": ["withholding"],
    "pinigil": ["withheld", "withholding"],
    "pinipigil": ["withholding"],
    "trabaho": ["work", "employment"],
    "nagtrabaho": ["work", "employment"],
    "nagtatrabaho": ["work", "employment"],
    "magtrabaho": ["work", "employment"],
    "pinagtrabaho": ["work", "employment"],
    "pinagtatrabaho": ["work", "employment"],
    "pasok": ["work"],
    "pinapasok": ["work"],
    "empleyo": ["employment"],
    "hanapbuhay": ["employment", "occupation"],
    "empleyado": ["employee"],
    "empleado": ["employee"],
    "manggagawa": ["worker"],
    "mangagawa": ["worker"],
    "trabahador": ["worker"],
    "amo": ["employer"],
    "patron": ["employer"],
    "boss": ["employer"],
    "kumpanya": ["establishment", "enterprise"],
    "kompanya": ["establishment", "enterprise"],
    "negosyo": ["enterprise", "establishment"],
    "oras": ["hours", "hours of work"],
    "shift": ["shift"],
    "iskedyul": ["schedule"],
    "schedule": ["schedule"],
    "walong oras": ["eight hours"],
    "8 oras": ["eight hours"],
    "overtime": ["overtime", "overtime work", "overtime pay"],
    "over": ["overtime"],
    "lampas": ["overtime"],
    "lagpas": ["overtime"],
    "sobra": ["overtime"],
    "extra": ["overtime"],
    "dagdag": ["additional compensation"],
    "undertime": ["undertime work"],
    "kulang-oras": ["undertime work"],
    "pahinga": ["rest", "rest period", "rest day"],
    "break": ["rest period", "meal periods"],
    "meal break": ["meal periods"],
    "kain": ["meal periods"],
    "tanghalian": ["meal periods"],
    "off": ["rest day"],
    "day off": ["rest day"],
    "dayoff": ["rest day"],
    "holiday": ["holiday"],
    "bakasyon": ["vacation leave"],
    "vacation": ["vacation leave"],
    "leave": ["leave"],
    "gabi": ["night", "night work", "night worker"],
    "pang-gabi": ["night work", "night worker"],
    "night": ["night work", "night worker"],
    "night shift": ["night work", "night worker"],
    "night differential": ["night shift differential"],
    "sakit": ["illness", "disease", "health", "medical"],
    "karamdaman": ["illness", "disease"],
    "kalusugan": ["health"],
    "medical": ["medical"],
    "doktor": ["physician"],
    "ospital": ["hospital"],
    "ospitalan": ["hospital"],
    "galing": ["health"],
    "buntis": ["pregnant", "maternity"],
    "pagbubuntis": ["pregnancy", "maternity"],
    "panganganak": ["childbirth", "maternity"],
    "manganak": ["childbirth", "maternity"],
    "maternity": ["maternity", "maternity leave"],
    "babae": ["woman", "women"],
    "kababaihan": ["women"],
    "babaeng": ["woman", "women"],
    "tanggal": ["termination", "dismissal"],
    "tinanggal": ["termination", "dismissal"],
    "natanggal": ["termination", "dismissal"],
    "tinatanggal": ["termination", "dismissal"],
    "tatanggalin": ["termination", "dismissal"],
    "pinaalis": ["termination", "dismissal"],
    "pinatanggal": ["termination", "dismissal"],
    "sinisante": ["dismissal"],
    "sinibak": ["dismissal"],
    "talsik": ["termination", "dismissal"],
    "sibak": ["dismissal"],
    "terminate": ["termination"],
    "termination": ["termination"],
    "dismissal": ["dismissal"],
    "regular": ["regular employment", "regular employee"],
    "permanente": ["regular employment"],
    "permanent": ["regular employment"],
    "probationary": ["probationary employment", "probationary employee"],
    "probation": ["probationary employment"],
    "casual": ["casual employment", "casual employee"],
    "contractual": ["contractual"],
    "kontraktwal": ["contractual"],
    "kontrata": ["contract"],
    "apprentice": ["apprentice", "apprenticeship"],
    "apprenticeship": ["apprenticeship"],
    "learner": ["learner"],
    "trainee": ["learner", "apprentice"],
    "balik": ["reinstatement"],
    "ibalik": ["reinstatement"],
    "reinstatement": ["reinstatement"],
    "backpay": ["backwages"],
    "backwages": ["backwages"],
    "separation": ["separation"],
    "retrenchment": ["retrenchment"],
    "redundancy": ["redundancy"],
    "layoff": ["layoff"],
    "resign": ["resignation"],
    "resigned": ["resignation"],
    "nagresign": ["resignation"],
    "magresign": ["resignation"],
    "bitiw": ["resignation"],
    "nagbitiw": ["resignation"],
    "pagbibitiw": ["resignation"],
    "hire": ["hire", "hiring"],
    "hiring": ["hiring"],
    "naghire": ["hiring"],
    "maghire": ["hiring"],
    "recruit": ["recruitment"],
    "recruitment": ["recruitment", "placement"],
    "nagrecruit": ["recruitment"],
    "magrecruit": ["recruitment"],
    "recruiter": ["recruiter"],
    "agency": ["agency"],
    "placement": ["placement"],
    "job": ["employment"],
    "hanap": ["employment"],
    "lisensya": ["license"],
    "license": ["license"],
    "permit": ["permit"],
    "pahintulot": ["authority"],
    "awtoridad": ["authority"],
    "rehistro": ["registration"],
    "rehistrasyon": ["registration"],
    "registration": ["registration"],
    "abroad": ["overseas employment"],
    "OFW": ["overseas employment"],
    "ofw": ["overseas employment"],
    "migrant": ["migrant"],
    "migrante": ["migrant"],
    "overseas": ["overseas employment"],
    "seaman": ["seaman"],
    "seafarer": ["seaman"],
    "illegal": ["illegal"],
    "ilegal": ["illegal"],
    "bawal": ["prohibited"],
    "ipinagbabawal": ["prohibited"],
    "scam": ["fraud"],
    "scammer": ["fraud"],
    "panloloko": ["fraud"],
    "manloloko": ["fraud"],
    "kaligtasan": ["safety"],
    "safety": ["safety"],
    "panganib": ["danger", "hazard"],
    "hazard": ["hazard"],
    "peligro": ["danger", "hazard"],
    "aksidente": ["accident"],
    "sugat": ["injury"],
    "injury": ["injury"],
    "diskriminasyon": ["discrimination"],
    "discrimination": ["discrimination"],
    "edad": ["age"],
    "kasarian": ["sex"],
    "sex": ["sex"],
    "lahi": ["race"],
    "creed": ["creed"],
    "unyon": ["union", "labor union", "labor organization"],
    "union": ["union", "labor union", "labor organization"],
    "samahan": ["labor organization"],
    "organisasyon": ["organization", "labor organization"],
    "membership": ["membership"],
    "member": ["member"],
    "dues": ["union dues"],
    "ambag": ["contributions"],
    "negosasyon": ["negotiation", "collective bargaining"],
    "bargaining": ["collective bargaining"],
    "CBA": ["collective bargaining agreement"],
    "cba": ["collective bargaining agreement"],
    "kasunduan": ["agreement"],
    "reklamo": ["complaint", "grievance"],
    "nagreklamo": ["complaint"],
    "magreklamo": ["complaint"],
    "complaint": ["complaint"],
    "kaso": ["case"],
    "alitan": ["dispute"],
    "away": ["dispute"],
    "gulo": ["dispute"],
    "grievance": ["grievance"],
    "areglo": ["settlement"],
    "ayusan": ["settlement"],
    "mediation": ["mediation"],
    "arbitration": ["arbitration"],
    "tagapamagitan": ["mediator"],
    "conciliation": ["conciliation"],
    "welga": ["strike"],
    "welgista": ["striker"],
    "nagwelga": ["strike"],
    "magwelga": ["strike"],
    "strike": ["strike"],
    "piket": ["picketing"],
    "picket": ["picketing"],
    "lockout": ["lockout"],
    "retiro": ["retirement"],
    "retire": ["retirement"],
    "nagretire": ["retirement"],
    "magretire": ["retirement"],
    "pagreretiro": ["retirement"],
    "karapatan": ["rights"],
    "tungkulin": ["duty"],
    "obligasyon": ["obligation"],
    "responsibilidad": ["responsibility"],
    "proteksyon": ["protection"],
    "seguridad": ["security"],
    "DOLE": ["Department of Labor and Employment"],
    "dole": ["Department of Labor and Employment"],
    "NLRC": ["National Labor Relations Commission"],
    "nlrc": ["National Labor Relations Commission"],
    "arbiter": ["Labor Arbiter"],
    "paggawa": ["labor"],
    "labor": ["labor"]
}